server:
  address: localhost
  port: 8080


spring:
  profiles:
    active: @package.environment@


  mail:
    host: smtp.exmail.qq.com
    username: xxxxx
    password: xxxxx
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true # 使用
          starttls: # 使用 SSL 安全协议，必须配置如下
            enable: true
            required: true
      port: 465  # 端口
      protocol: smtps # 协议

  redis:
    host: localhost
    password: pcmd

mail:
  from: xxxxx


mybatis:
  mapper-locations: "classpath:META-INF/sqlmap/*.xml"
  type-aliases-package: "com.mwgroup.block.entity"



logging:
  level:
    org.springframework.web: info        #Spring框架中的日志级别
    com.mwgroup.block: DEBUG

