server:
  port: 8080
swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: "Spring Boot 测试使用 Swagger2 构建RESTful API"
  contact:
    # 维护人
    name: "yunlingfly"
    email: "508821881@qq.com"
    url: "https://www.yunlingfly.cn"
  # 版本
  version: "1.0"
  # 描述
  description: "API 描述"
  # swagger扫描的基础包，默认：全扫描
  base-package: "com.example.demo.controller"
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
#  exclude-path: ""
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"

#MySQL数据库配置
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

    #Spring boot视图配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    #Mybatis的相关配置
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml

    #分页pagehelper的相关配置
#logging:
#  level: debug
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  page-size-zero: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
